In [1]:
from sklearn.pipeline import Pipeline
##feature Scaling
from sklearn.preprocessing import StandardScaler ## tran
from sklearn.linear_model import LogisticRegression ## estimator

In [4]:
steps=[("standard_scaler",StandardScaler()),
       ("classifier",LogisticRegression())]

In [5]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [7]:
pipe=Pipeline(steps)

In [8]:
### visualize Pipeline
from sklearn import set_config


In [9]:
set_config(display="diagram")

In [10]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [15]:
### creating a dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [16]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y ,test_size=0.33,random_state=42)

In [17]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [18]:
y_pred=pipe.predict(X_test)

In [19]:
y_pred

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,

In [ ]:
### 
#Displaying a pipeline with standard scalar ,dimensinality reduction and then estimator 

In [20]:
from sklearn.decomposition import PCA 
from sklearn.svm import SVC

In [21]:
step=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]

In [22]:
pipe2=Pipeline(step)

In [24]:
pipe2['scaling'].fit_transform(X_train)

array([[ 0.85833735,  0.76937753, -1.23482223, ..., -0.64668514,
        -0.43323746,  1.33553988],
       [-1.28473133,  0.01305467,  1.52224281, ..., -3.0625489 ,
         1.45813568, -0.06355517],
       [-0.40199919, -0.20164839,  0.91118043, ..., -0.99705186,
        -1.71645714,  0.81239327],
       ...,
       [ 0.18055112,  1.25451308,  2.01900642, ...,  0.45609463,
         0.94219364, -1.32212919],
       [-0.86231338, -0.05176283, -0.94592938, ...,  1.03283988,
         0.25031924, -0.44267023],
       [ 0.32752278,  0.0471093 ,  0.72167651, ...,  1.29679026,
        -1.23611876,  0.69054236]])

In [25]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [26]:
pipe2.predict(X_test)

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,

### complex examples of columns transformer

In [29]:
from sklearn.impute import SimpleImputer
import numpy as np

In [32]:
## num
numeric_processor=Pipeline(steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),
                                  ("scaler",StandardScaler())])

In [33]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [34]:
##categorical Processing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(steps=[("imputation_constand",SimpleImputer(fill_value="missing",strategy="constand")),
                                  ("onehot",OneHotEncoder(handle_unknown="ignore"))])


In [35]:
categorical_processor

Pipeline(steps=[('imputation_constand',
                 SimpleImputer(fill_value='missing', strategy='constand')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [ ]:
### 

In [36]:
##combine processing technique
from sklearn.compose import ColumnTransformer


In [37]:
preprocessor =ColumnTransformer([("categorical",categorical_processor,["gender","City"]),
                   ("numerical",numeric_processor,["age","height"])])

In [38]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constand',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constand')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [39]:
from sklearn.pipeline import make_pipeline


In [42]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [43]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constand',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constand')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])